name: your_app_name
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
     # or latest version


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
